version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    container_name: beaverhacks
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma_db